# apiVersion: Specifies which version of the Kubernetes API to use
# v1 is the core/stable API group that includes fundamental resources
apiVersion: v1

# kind: Defines the type of Kubernetes resource being created
# Secret is used to store sensitive information like keys, passwords, and tokens
kind: Secret

# metadata: Contains identifying information about the resource
# Including its name, namespace, and other optional attributes
metadata:
  # name: The identifier for this secret
  # Must be unique within the namespace
  name: secret
  # namespace: Specifies which namespace this secret belongs to
  # References the 'experiment' namespace we created earlier
  namespace: experiment

# data: Contains the actual secret key-value pairs
# Values must be base64 encoded before being stored
data:
  # api-key: The API key for Typesense authentication
  # Currently empty, needs to be populated with a base64-encoded value
  api-key: ""
